### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by SilasK** [dutilh/CAT#13]
Hey @bastiaanvonmeijenfeldt 

I try to download the NR database. I tried it on the head node, but I don't have enough memory. 
Strangely your code didn't end with an error. 

So, I would need to perform this on my cluster system. Do you have any idea how much memory and time it would need to generate the diamond database?

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi @SilasK ,

Yes, you need quite a lot of memory for the database prepare step (around 90GB atm)! The error is difficult to catch since it is raised not by Python but by the OS. This is something more users have mentioned, so we are working on a solution. This entails:

1) I'm building in an available memory check when running the 'prepare' utility. Any system with less than 100GB of RAM will exit. This is not a true solution but it is more user friendly than it is now. I plan to put this online in the coming days.
2) We are putting our own database files on our server open for everybody to download in case you don't have enough memory at your disposal. Will also be online in the coming days.
3) We are also making the prepare utility more memory friendly, but this is a longer term to do.

Best wishes,

Bastiaan

**Comment by SilasK** [comment]
I think if you use the "strict mode" for bash commands it should exit with an error when hitting the problem of too much memory. 

`set -euo pipefail ; bash command`

[mere here](http://redsymbol.net/articles/unofficial-bash-strict-mode/)
