### ISSUE TITLE
protein input

### ISSUE THREAD

**Issue by SilasK** [dutilh/CAT#14]
@bastiaanvonmeijenfeldt 
The option to input the genes directly to cat is nice. But what exactly do you mean by concatenated genes?

**Comment by bastiaanvonmeijenfeldt** [comment]
@SilasK 
Are you talking about bin classification? For bin classification we currently construct one large file with all proteins found in all bins concatenated, as opposed to one protein fasta per bin. We also change the fasta identifiers to couple the proteins to the bins in which they are found. Thus if you'd supply such a file to BAT, it can start after gene calling, but since the syntax is strict right now we suggest to use concatenated files that have been generated by BAT before. If you want to make a concatenated protein file yourself without the help of BAT, you're protein headers should be ">${BIN}_${CONTIG_NAME}" and that should do the trick!

**Comment by SilasK** [comment]
Ok, this is pretty standard. I misunderstood "concatenated" as making one continuous sequence of all proteins.

**Comment by VGalata** [comment]
Would it be possible to get more information on the expected naming scheme?

I have a directory containing the bin FASTAs (file name `bin<num>.fna`, record IDs `scaffold<num>`) and a protein FASTA containing the proteins from the bins (record IDs `bin<num>_scaffold<num>_<num>`).

CATBAT does find all the bin FASTAs but cannot process the protein IDs. From the log file:

```
...
[2019-11-22 14:27:39.560892] 150 bin(s) found!
[2019-11-22 14:27:39.561897] Parsing ORF file mypath/bins.faa
[2019-11-22 14:27:41.067547] ERROR: found a protein in the predicted proteins fasta file that can not be traced back to one of the contigs in the contigs fasta file: bin052_scaffold1_1. Proteins should be named contig_name_#.
```
The file `bin052.fna` contains the `scaffold1` sequence, so the ID should is valid.

Do you have an idea why the tools is not able to process the IDs?

Thanks in advance!

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi @VGalata,

Currently BAT makes the contig/ORF connection by assuming that everything before the last underscore is the contig name. So BAT in this case would not recognise the contigs within a bin as they are called scaffold1 instead of bin052_scaffold1. Renaming the contigs within the bins to `${bin_name}_${contig_name}` would solve this error. (If you'd run BAT from the start, i.e. with ORF production included, a new separate `.fasta` file is generated with the contigs renamed in this fashion.)

We are still evaluating how people use CAT and BAT so thanks for this question! In a future update we might address this specific confusion.

Hope this helps, please let me know if you encounter further problems!

Best wishes,

Bastiaan

**Comment by bastiaanvonmeijenfeldt** [comment]
I'm sorry I spoke too soon! BAT already checks for this `${bin_name}_${contig_name}` construct... I'm looking into it now, but please do not put much effort into changing your contig names yet...

**Comment by VGalata** [comment]
Thank you for the fast reply!

Okay.... I just tried to remove the bin ID from the protein IDs and it did not work either. Guess the bin ID is essential. I would then wait for our update. Thanks again for looking into this!

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi @VGalata,

It turns out I leave the suffix in when renaming a contig! So instead of calling it `bin052_scaffold1` it should actually be called `bin052.fna_scaffold1`. Could you try whether this works for you?

As a side note, I do this because it allows you to have multiple bins with the same name but with different suffices in the same folder. It's a super obscure use case but pretty useful for debugging purposes. I'm sorry for the confusion and hope this works for you!

Best wishes,

Bastiaan

**Comment by VGalata** [comment]
The bins FASTAs (named `bin<num>.fna`) have now IDs like this `>bin<num>.fna_scaffold<num>` and the proteins have IDs `>bin<num>.fna_scaffold<num>_<num>`. But I still get the error:
```
[2019-11-22 16:12:07.203192] ERROR: found a protein in the predicted proteins fasta file that can not be traced back to one of the contigs in the contigs fasta file: bin052.fna_scaffold1_1. Proteins should be named contig_name_#.
```

Do I miss something? :/

**Comment by bastiaanvonmeijenfeldt** [comment]
The scaffolds in the bins should just be called `scaffold<num>`, only the proteins should be renamed!

**Comment by VGalata** [comment]
It worked! Thank you!
