### ISSUE TITLE
Can I adjust memory usage and temporary disk size of Diamond search step?

### ISSUE THREAD

**Issue by ilnamkang** [dutilh/CAT#15]
Hi,

I'm trying to use CAT for analyses of my metagenomic contigs (~110,000 contigs, total length of ~400 Mbp).

I've run CAT for my data using the database file downloaded from http://tbb.bio.uu.nl/bastiaan/CAT_prepare/, on a Linux server with 256 GB memory and ~280 GB of empty HDD space.

Prodigal worked nice and predicted ~450,000 proteins.

But, Diamond finished abnormally with the following error messages, after running ~10 hours using ~10 GB of memory.

"No space left on device
Error: Error writing file diamond-tmp-NNi5RC"

As far as I know, we can adjust memory usage and temporary disk space (and location) when using Diamond. And, to my knowledge, Diamond takes less time when using more memory.

Are there any methods to adjust memory usage and temporary disk size of Diamond search step of CAT?

Best,
Ilnam

**Comment by ilnamkang** [comment]
Hi,

I've successfully increased the memory usage of Diamond search step by adding '--block-size' and '--index-chunks' options to 'shared.py' file.

I've also added '--sensitive' option to 'shared.py' file without any errors. According to the Diamond manual, the '--sensitive' option is recommended for aligning longer sequences, as the default mode is mainly designed for 30-40 aa fragments.

Best,
Ilnam

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi Ilnam,

Thanks for your question and also for your direct solution!
Indeed we designed CAT in such a way that if you're a little familiar with Python you should be able to make these adjustments yourself. However we have also gotten more questions about temporary disk space so I'm thinking about how we can implement this in the command line interface in a user-understandable fashion (I'm thinking '--low-disk-usage' for now).

Regarding the '--sensitive' option; we have extensively tested this in earlier iterations and didn't see a noticeable increase with regards to precision, hence did not use this as default. I guess because we aggregate a lot of hits and don't make inferences about single ones. However I will probably add the option in the next version, because people keep asking for it and maybe for their specific question it does make a difference.

So thanks for your feedback and stay tuned!

Best wishes,

Bastiaan

**Comment by bastiaanvonmeijenfeldt** [comment]
Closed issue for now since it's put on the wish list.

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi Ilnam,

The latest version of CAT/BAT (v4.4) includes tuning of these DIAMOND parameters natively! Try it out!

Best wishes,

Bastiaan
