### ISSUE TITLE
process output

### ISSUE THREAD

**Issue by SilasK** [dutilh/CAT#17]
Hey @bastiaanvonmeijenfeldt , 

I run CAT bin on my bins and got the lineages and the official taxonomic names. I see you are very cautios not to overclassify. 

To process the output I would like to 
1. visualize the output in a tree, e.g by using the taxid
2. get a short taxonomic name for each bin, e.g. `Bacteroides*`

Unfortunately this is more complicated than I thougth. Because, neither the lineages nor the names are in a easy to read format, e.g. table. 

The lineage countan stars, so they are no longer numbers. 
The names come allways with the score e.g. `Escherichia: 0.8`
Of course I can extract the information I want, but I thoght It would make sense to ask you to change the output format. 

Then there is the problem of double annotations, which I don't completly understand why this happends. At least it makes it almost impossible to computationally add a unique name to each bin. 

what do you think?

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi Silas,

We made the output format like this by design, and might change it depending on how people will use it, but will probably not change it until the paper is published. To give you some idea about why some bins have multiple classifications, we have put the paper we are working on as a preprint online already, see https://www.biorxiv.org/content/10.1101/530188v1. If you really don't want any double classifications you can put the f parameter to >= 0.5, but this will make all classifications more conservative, and I think that for bins there is no need to be too conservative.

Thus what I would advice is take a low f (f=0.3, or you can even go to 0.1 if you think it's even too conservative), and only in the case of double classification classify the bin as if f=0.5 just for that bin. This will cost you a little more parsing of the output file, and I'm thinking of putting that in the next version of BAT as an option, but again won't do that before the paper is published.

Regarding of parsing of the output files (also as a help for others): they are tab-separated tables, and each entry is again separated by ':' and ';'. So you can split on those characters, and rstrip('*') to get rid of the asterisk.

Again, I'm thinking of whether we should change the output format or have an option to output it differently, but will not implement this before the paper is published.

Let me know via mail if I can help you with parsing the files Silas!

Bastiaan
