### ISSUE TITLE
Can we parallelize the diamond search?

### ISSUE THREAD

**Issue by SilasK** [dutilh/CAT#18]
@bastiaanvonmeijenfeldt 
I'm integrating CAT in my snakemake pipeline. I would like to parallelize the taxonomic annotation, e.g. submit the annotation of each bin to another cluster node. 

Would it be possible to add the option that CAT bin an take a single fasta file as input not only a bin folder?

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi Silas,

Thanks for this feedback, I understand the usability of this and will include it in a future version of BAT. For now, we focus on publishing the paper, so I will not include this in a timescale of weeks I think... Of course you can sort of hack this in for now by placing each bin in a single folder.
I'll keep you update if I have a better time frame!

**Comment by bastiaanvonmeijenfeldt** [comment]
Closed this issue for now since it's placed on the wish list.
Will probably put the wish list online as well soon.

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi @SilasK,

I have added single bin mode to BAT! It's currently live in v4.5. I hope you like it!

As a reference for other users that might read this; if you have multiple MAGs you want to classify, running BAT in single bin mode is probably (a lot) slower than in the familiar multiple bin mode.

Thus:

```shell
$ ./CAT bins -b {bin folder} ...
```

is much faster than:

```shell
$ for FILE in bin_folder/*.fa; do
    ./CAT bin -b ${FILE} ...
done
```

The reason is that the most time limiting step is the DIAMOND alignment, not the classification algorithm itself which is really fast. And because of how DIAMOND works, searching twice as many sequences in a single run will be a lot faster than dividing them over two.

Having said that, single bin mode can be really useful. For one, it allows you to both classify the MAG and the individual contigs within it with a single alignment. Also, if you only have a single MAG it's just easier to do it like this than to have to put it in a single directory where no other files with the same suffix are allowed, etc. And of course for people that build pipelines it might simplify their workflow a lot.

Let me know what you think of our current implementation!
