### ISSUE TITLE
Split concatenated files per bin

### ISSUE THREAD

**Issue by GeoMicroSoares** [dutilh/CAT#21]
Hi there,

I want to use the final `.gff` and `.faa` after running BAT. How can I now split these files by bin?

Thanks!

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi @GeoMicroSoares,

There is no build-in feature in BAT to do this, however it can be done with a little code from yourself!

BAT renames the contigs within bins to "{BIN_NAME}_{CONTIG_NAME}". Thus for example scaffold_1 in bin.76.fna will be renamed to "bin.76_scaffold_1" and in the protein .faa file these proteins will be named "bin.76_scaffold_1_1", "bin.76_scaffold_1_2", etc.

So say all your bins **do not contain underscores**, parsing the .faa file with Python would go somewhere along these lines:

```python3
#!/usr/bin/env python3

import os
import sys

bin_trace = set()
with open('out.BAT.concatenated.predicted_proteins.faa', 'r') as f:
    for line in f:
        if line.startswith('>'):
            # The split('_') is the reason why there shouldn't be an underscore in the bin name.
            bin_ = line.split('_')[0].lstrip('>')
            
            out_file = f'{bin_}.proteins.faa'
            
            if bin_ not in bin_trace:
                # Just be sure to not override an existing file.
                if os.path.isfile(out_file):
                    sys.exit(f'Strange, the file {out_file} exists already! Quitting...')
                    
                # Create a fresh new file.
                with open(out_file, 'w') as outf:
                    pass
                bin_trace.add(bin_)
                
        with open(out_file, 'a') as outf:
            outf.write(line)
```

If the bin names do contain underscores your code should look a little different to accommodate for this (what are your bin names?).
Also, loading the file into memory first is a little cleaner because you don't have to open the output file again for every line, but I think this code is the most understandable as a reference. Parsing the .gff file goes a little different but with similar logic. 

Hope this helps! Send me an email if this doesn't work for you!

Bastiaan
