### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by tigerxu** [dutilh/CAT#27]
Hi,

CAT is very nice for classification of MAGs. I have tried to use CAT bins on several datasets containing <20 bins. All runs are worked! However, I met a problem of program interruption when I run a larget dataset contain ~400 bins. The running log file is attached below.
[run_CAT_bins_201911061143.nohup.txt](https://github.com/dutilh/CAT/files/3812450/run_CAT_bins_201911061143.nohup.txt)

Any help would be much appreciated!
Zhuofei

**Comment by bastiaanvonmeijenfeldt** [comment]
Dear @tigerxu,

There seems to be something strange going on with your DIAMOND file. The error indicates that at some point in the file there are less than 12 columns. My guess is that the previous DIAMOND run did not finish correctly, but I cannot see this in the log file as it's generated in a previous run.

One reason this might happen with larger datasets is that you may have run out of disk space (the DIAMOND alignments become quite large quickly). If this is the case, you might find a solution here: https://github.com/dutilh/CAT#setting-the-diamond---top-parameter.

Hope this helps, closing the issue for now because the error is not within BAT but within a previous DIAMOND alignment step. Don't hestitate to open it again if this did not solve your problem!

Best wishes,

Bastiaan
