### ISSUE TITLE
Using gzip for output files

### ISSUE THREAD

**Issue by Finesim97** [dutilh/CAT#30]
It would be nice to have the option to compress the output files, while this would increase the  computational load, it would reduce the HDD space requirements.

I could start to work on a PR for that.

Best wishes,
Lukas Jansen

**Comment by Finesim97** [comment]
DIAMOND also has a flag to compress the output

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi @Finesim97,

We think compression of the output files is a great idea.
Please go ahead and fork our code! :) As far as the DIAMOND compression format goes, I have looked into this but it doesn't seem that trivial to parse the files later.

Best wishes,

Bastiaan

**Comment by bastiaanvonmeijenfeldt** [comment]
I have added gzip support for the alignment files. There is `--compress` flag that will gzip the DIAMOND output, and parsing of gzip compressed alignment files is now also supported.

Since the alignment file is the big disk consumer I started with it. If users want compression of other output files we can also implement that in future releases.
