### ISSUE TITLE
Taxonomy output

### ISSUE THREAD

**Issue by Alema91** [dutilh/CAT#36]
There is a way to represent with a taxonomy plot (like Krona) the output generated after CAT add_names function?

Thank you so much

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi @Alema91,

Currently we do not allow for a Krona visualisation of CAT output. The reason is that the CAT output represents the **number of contigs** classified to a certain taxon rather than the **abundance** of that taxon in the metagenome.

The difference between number of contigs and abundance is important because some taxa may represent a lot of contigs and/or have a long sequence length overall but constitute only a small part of the total metagenome.

In order to get from the CAT output to true abundances you'll have to:

1) map the original sequencing reads bag to the contigs,
2) count how many reads are represented by each taxon,
3) divide this number by the total sequence length represented by the taxon.

We routinely do this ourselves but have not implemented this in CAT just yet. We will in a future update though (I'm now thinking RAT for Read Annotation Tool)!

Hope this helps,

Best wishes,

Bastiaan

**Comment by Alema91** [comment]
Thank you so much for your respond! I certainly follow your advice and thank you again for this wonderful program.

**Comment by bpenaud** [comment]
Hello,

I am a user of CAT/BAT/RAT, thank you for these software. Now that RAT is out, I was wondering if there is a script to convert output to krona format?

Thank you,
Benjamin
