### ISSUE TITLE
Preparing a database based on a refseq file

### ISSUE THREAD

**Issue by michaelpeeri** [dutilh/CAT#42]
Hello,

Is there a way to prepare an input database from a refseq file, as you describe in the section "benchmark 2" of your manuscript? If so, how does one provide the mapping between the headers and the taxonomic identifiers (should I prepare my own Prot.accession2taxid file and in what format?).

Thank you!

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi @michaelpeeri,

Yes, using RefSeq (protein) is a possibility, and not too difficult. However it requires some change from the default setup to do it correctly.
The trick is to reconstruct the database anew, and let CAT think that your RefSeq fasta file is actually the NR fasta file it is looking for. The `CAT prepare` command has a useful `--existing` flag to do just this.

**A little explanation that will help you with debugging this:**
If you have the RefSeq protein fasta, - let's say this file is called `RefSeq.faa` on your system -, its headers contain accession numbers, like so:

>\>NP_001006011.1 pleckstrin homology-like domain family A member 1 [Danio rerio]

CAT will parse those just fine, whether they come from RefSeq or NR. However CAT prepare by default makes the database files based on NR; it will download NR and the taxonomy files, etc.  If you run `CAT prepare --existing`, CAT will search in the folder that you supply for files that are already downloaded, and if so won't download those again. It will specifically look for a file that ends with `nr.gz`. So if you gzip your RefSeq file, rename it, and place it in the database folder, it should work!

```
$ gzip RefSeq.faa
$ mv RefSeq.faa.gz RefSeq.faa.nr.gz
$ mkdir CAT_database
$ mv RefSeq.faa.nr.gz CAT_database
$
$ CAT prepare --existing -d CAT_database
```
Of course it would be a good idea to have the taxonomy files and RefSeq downloaded at the same day.

I got this question from more people. If it turns out CAT is used often with RefSeq we may make that an 'official' option. But for now this hack should work! Let me know if you run into any trouble.

Bastiaan

**Comment by michaelpeeri** [comment]
Thanks for your help!

michael
