### ISSUE TITLE
Check path to diamond

### ISSUE THREAD

**Issue by shiva309** [dutilh/CAT#6]
I have downloaded the taxonomy files(names.dmp, nodes.dmp and prot.accesion2taxid) which are all placed in the same folder and created nr.dmnd from nr.faa. I have specified the path(once in the script) to diamond, prodigal and to taxonomy files but I keep getting an error that **Please check path to diamond, presence information about database location or fasta file with coded proteins**.  I cannot figure out what is wrong? Thank you in advance.

**Comment by kseniaarkhipova** [comment]
Hi shiva309,
Can you send me your command for CAT and lines of code in script you changed?
Thanks,
Ksenia

**Comment by shiva309** [comment]
My CAT command is CAT --fna sample.fasta --prefix sample
I changed the following lines, I have specified path for diamond, prodigal and taxonomy files, also I have specified my database.
#Paths to diamond, prodigal binaries and taxonomy files should be absolute.
path_to_diamond = '/CAT/'
path_to_prodigal = '/CAT/'
path_to_taxonomy_files="/CAT/CAT-master/"
#Optional, by providing the absolute path to database and database name below, there is no need to provide -db option
#For example like db='/home/dir1/dir2/database.dmnd'
db='/CAT/CAT-master/nr.dmnd'

Thank you

**Comment by kseniaarkhipova** [comment]
Try to run diamond separately in command line as you have it in quotes, please. Because for me your path does not look like absolute. It usually starts like /home/username/other_directories/. The problem is that CAT cannot run prodigal and diamond for you. If you will be able to run them from command line separately - just add this path (but without executables - 'diamond' or 'prodigal' at the end of the command) into CAT and run it again.

**Comment by shiva309** [comment]
I didn't mention the full path but in earlier but in the script I have specified the full path and when I run diamond and prodigal separately they work. I am able to run CAT -h and then when I specify input file, prodigal runs because the predicted_prot.faa and orfs.gff files are created but the alignment_diamond file is empty. I know diamond path is correct because I used it to create the nr.dmnd file from nr.faa

**Comment by kseniaarkhipova** [comment]
Once again, the problem is that CAT does not see diamond (and likely prodigal too) with paths you specified inside script. It is quite difficult to help you if you do not show what you exactly did. But '/CAT/' is not an absolute path to executable. Add inside quotations inside CAT commands for prodigal and diamond how you can run them from command line For example, if you run diamond from command line like this:

/home/username/Programms/diamond/diamond help 

insert into CAT this like

path_to_diamond = '/home/username/Programms/diamond/'

Please do the same for prodigal and correct paths correspondingly for diamond database and directory with taxonomy files

Good luck!
